### ISSUE TITLE
Readme-recommended "bootstrap-debian" role no longer available

### ISSUE THREAD

**Issue by caspark** [jnv/ansible-role-unattended-upgrades#21]
It seems that @cederberg has deleted his https://github.com/cederberg/ansible-bootstrap role.

Would you happen to have a clone or snapshot of it? Otherwise, references to it should be removed from the README.

(I had a snapshot of it - but sadly I deleted it to get the latest version of each role, only to be unable to download it!)

**Comment by cederberg** [comment]
Wasn't much in that deleted repo. A script similar to this one:

```shell
#!/bin/sh

PKG=$1
DEBIAN_FRONTEND="noninteractive"
export DEBIAN_FRONTEND

if dpkg --status $PKG > /dev/null 2>&1 ; then
    exit 0
fi

echo "Installing $PKG..."
(apt-get --yes update && apt-get --yes install $PKG) > /dev/null 2>&1
exit $?
```

And a small action like so:

```
- name: Install minimal Ansible requirements
  script: install_missing_package.sh {{item}}
  register: res
  changed_when: "res.stdout.startswith('Install')"
  with_items:
     - python
     - python-apt
     - python-pycurl
     - aptitude
```

Better to copy this into your own project if you need it. Or push something upstream. Kind of sad that Ansible cannot bootstrap a host into management...
