### ISSUE TITLE
Deprecation Warning for install update-notifier-common task

### ISSUE THREAD

**Issue by dmp1ce** [jnv/ansible-role-unattended-upgrades#61]
I get the following warning when running my playbook.

ansible version `2.8.0`
jnv.unattended-upgrades version: `v1.7.0`

```
TASK [jnv.unattended-upgrades : install update-notifier-common] ******************************************************************************************************************************************************************************
[DEPRECATION WARNING]: evaluating unattended_automatic_reboot as a bare variable, this behaviour will go away and you might need to add |bool to the expression in the future. Also see CONDITIONAL_BARE_VARS configuration toggle.. This     
feature will be removed in version 2.12. Deprecation warnings can be disabled by setting deprecation_warnings=False in ansible.cfg. 
```

My role definition:

```
    - role: jnv.unattended-upgrades
      vars:
        unattended_origins_patterns:
          - 'origin=Ubuntu,archive=${distro_codename}-security'
        unattended_automatic_reboot: true
      when: "unattended_upgrades|bool"
```
