### ISSUE TITLE
Missing Unattended-Upgrade::Sender parameter

### ISSUE THREAD

**Issue by sberthelot** [jnv/ansible-role-unattended-upgrades#63]
The "Unattended-Upgrade::Sender" is missing from available parameters.

The default, at least on Ubuntu is "root" which makes the mails sent go directly to Junk folder (at best or in trash for some recipients...)

Can you please add this parameters to vars and template ?

**Comment by inn0kenty** [comment]
```yaml
  post_tasks:
  - name: fix sender
    lineinfile:
      dest: /etc/apt/apt.conf.d/50unattended-upgrades
      regexp: "^Unattended-Upgrade::Sender"
      line: 'Unattended-Upgrade::Sender "user@example.org";'
      state: present
```
