### ISSUE TITLE
How to deal with the 10Periodic file in /etc/apt/apt.conf.d/

### ISSUE THREAD

**Issue by gittur** [jnv/ansible-role-unattended-upgrades#75]
Hello,

I still have the `10Periodic` file present which overwrites 20auto-upgrade. Can we add a task to delete the file when the playbook runs, instead of using the one-shot command?

**Comment by jnv** [comment]
Hi, what's the issue here? Is the file being added to your system regularly or why is one-shot command not sufficient?

I would prefer not to add any implicit, destructive operations to this role. It is documented precisely for this reason as a note. You can always add a file task on your own:

```
- name: Remove /etc/apt/apt.conf.d/10periodic
  file:
    state: absent
    path: "/etc/apt/apt.conf.d/10periodic"
```

(Not sure about the capitalization though, you are mentioning that the file is named `10Periodic` but it used to be `10periodic` – lowercase 'p'. Maybe that's your issue here?)
