### ISSUE TITLE
APT's cron file missing

### ISSUE THREAD

**Issue by chmac** [jnv/ansible-role-unattended-upgrades#9]
Not sure it's really an issue with this role, maybe more the host system, but I'll post it here anyway.

I have 2 systems where `/etc/cron.daily/apt` does not exist and is instead called `/etc/cron.daily/apt.disabled`. In this situation, the unattended-upgrades package does not get run.

Maybe there could be a check in this role to make sure that the necessary cron files exist? I'm not sure if they are standard across distributions though, so understand if it's not practical.

**Comment by jnv** [comment]
Thanks for the report Callum!

This is indeed strange, maybe there is some postinstall configuration required. Could you please specify what distribution and version do you use (and whether you recently did dist-upgrade)? I'd like to check the source package.

**Comment by chmac** [comment]
It's Ubuntu 14.04 from owned-networks.net. I have a handful of other 14.04 machines and they have apt's cron file enabled by default. I read somewhere that maybe cheap VPS providers disable a load of stuff in cron.daily to save CPU cycles! :-)

It seems like it's an unlikely scenario, not sure if it really makes sense to include a test in the role or not. I added my own test to the playbook to rename the file from `apt.disabled` to `apt` if it doesn't exist. Of course that will fail if the disabled version doesn't exist!

**Comment by jnv** [comment]
I see, this was also reported in here: http://askubuntu.com/questions/530133/cron-jobs-are-disabled-on-clean-installation-of-14-04

I wonder how the provider makes this change: either they provide a modified package through a mirror (which seems unlikely), or it is already in the image – as a preinstalled file, a file diversion or as a separate process which renames these files.

Anyway I don't think we should attempt to fix this edge case through this role. I'd recommend to create a new role for renaming the file which might depend on this role for easier updates and reusability. And also question your provider about their decisions.

Moving the file should be a two phase process, e.g.:

```yaml
- name: check if apt.disabled exists
  stat: path=/etc/cron.daily/apt.disabled
  register: apt_disabled

- name: reenable apt script for daily cron
  command: mv /etc/cron.daily/apt.disabled /etc/cron.daily/apt
  when: apt_disabled.stat.exists
```

(see [stat module](http://docs.ansible.com/stat_module.html))

I will close this issue, let me know if this is okay.
